package Exam1App;


/**
* Exam1App/Exam1Operations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Exam1.idl
* Saturday, February 6, 2021 12:48:59 PM SGT
*/

public interface Exam1Operations 
{
  int gcd (int num1, int num2);
  int countVow (String a);
  int countCons (String a);
  String palindrome (String n);
  void shutdown ();
} // interface Exam1Operations
