package Exam1App;


/**
* Exam1App/Exam1.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Exam1.idl
* Saturday, February 6, 2021 12:48:59 PM SGT
*/

public interface Exam1 extends Exam1Operations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Exam1
