package Exam1App;


/**
* Exam1App/Exam1POA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Exam1.idl
* Saturday, February 6, 2021 12:48:59 PM SGT
*/

public abstract class Exam1POA extends org.omg.PortableServer.Servant
 implements Exam1App.Exam1Operations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("gcd", new java.lang.Integer (0));
    _methods.put ("countVow", new java.lang.Integer (1));
    _methods.put ("countCons", new java.lang.Integer (2));
    _methods.put ("palindrome", new java.lang.Integer (3));
    _methods.put ("shutdown", new java.lang.Integer (4));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Exam1App/Exam1/gcd
       {
         int num1 = in.read_long ();
         int num2 = in.read_long ();
         int $result = (int)0;
         $result = this.gcd (num1, num2);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 1:  // Exam1App/Exam1/countVow
       {
         String a = in.read_string ();
         int $result = (int)0;
         $result = this.countVow (a);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 2:  // Exam1App/Exam1/countCons
       {
         String a = in.read_string ();
         int $result = (int)0;
         $result = this.countCons (a);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 3:  // Exam1App/Exam1/palindrome
       {
         String n = in.read_string ();
         String $result = null;
         $result = this.palindrome (n);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 4:  // Exam1App/Exam1/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Exam1App/Exam1:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Exam1 _this() 
  {
    return Exam1Helper.narrow(
    super._this_object());
  }

  public Exam1 _this(org.omg.CORBA.ORB orb) 
  {
    return Exam1Helper.narrow(
    super._this_object(orb));
  }


} // class Exam1POA
